export const uiText={
UZ:{life:'Hayot lavhalari',lifeLabel:'TA’LIM VA KARYERA',sample:'Namuna',add:'Lavha qo‘shish',edit:'Tahrirlash',remove:'O‘chirish',save:'Saqlash',saved:'Saqlandi',saving:'Saqlanmoqda…',cancel:'Bekor qilish',date:'Sana',title:'Sarlavha',description:'Tavsif',image:'Rasm',loading:'Yuklanmoqda…',unavailable:'Ma’lumotni yuklab bo‘lmadi.',empty:'Hozircha ma’lumot yo‘q.',retry:'Qayta urinish',together:'Birga ishlaylik',credentials:'SERTIFIKATLAR',tools:'VOSITALAR VA YONDASHUV',journey:'ISH TAJRIBASI',selected:'TANLANGAN ISHLAR',talk:'BOG‘LANISH',contacts:'ALOQA MA’LUMOTLARI',required:'* Majburiy maydonlar',sending:'Yuborilmoqda…',sent:'Xabaringiz yuborildi. Rahmat!',failed:'Xabar yuborilmadi. Qayta urinib ko‘ring.',top:'Yuqoriga',light:'Yorug‘ mavzu',dark:'Qorong‘i mavzu',present:'hozir',studying:'O‘qish davom etmoqda',viewCertificate:'Sertifikatni ko‘rish',navigation:'Sayt navigatsiyasi',openMenu:'Menyuni ochish',closeMenu:'Menyuni yopish',sampleNote:'Bu vaqtinchalik namuna, haqiqiy voqea emas.'},
ENG:{life:'Life moments',lifeLabel:'EDUCATION & CAREER',sample:'Sample',add:'Add moment',edit:'Edit',remove:'Delete',save:'Save',saved:'Saved',saving:'Saving…',cancel:'Cancel',date:'Date',title:'Title',description:'Description',image:'Image',loading:'Loading…',unavailable:'Could not load the content.',empty:'No content yet.',retry:'Try again',together:'Let’s work together',credentials:'CREDENTIALS',tools:'TOOLS & APPROACH',journey:'EXPERIENCE',selected:'SELECTED WORK',talk:'GET IN TOUCH',contacts:'CONTACTS',required:'* Required fields',sending:'Sending…',sent:'Your message has been sent. Thank you!',failed:'Message not sent. Please try again.',top:'Back to top',light:'Light theme',dark:'Dark theme',present:'present',studying:'Currently studying',viewCertificate:'View certificate',navigation:'Site navigation',openMenu:'Open menu',closeMenu:'Close menu',sampleNote:'Temporary sample, not a real event.'},
RU:{life:'Моменты жизни',lifeLabel:'УЧЁБА И КАРЬЕРА',sample:'Пример',add:'Добавить момент',edit:'Редактировать',remove:'Удалить',save:'Сохранить',saved:'Сохранено',saving:'Сохранение…',cancel:'Отмена',date:'Дата',title:'Заголовок',description:'Описание',image:'Изображение',loading:'Загрузка…',unavailable:'Не удалось загрузить данные.',empty:'Данных пока нет.',retry:'Повторить',together:'Давайте работать вместе',credentials:'СЕРТИФИКАТЫ',tools:'ИНСТРУМЕНТЫ И ПОДХОД',journey:'ОПЫТ РАБОТЫ',selected:'ИЗБРАННЫЕ РАБОТЫ',talk:'СВЯЗАТЬСЯ',contacts:'КОНТАКТЫ',required:'* Обязательные поля',sending:'Отправка…',sent:'Сообщение отправлено. Спасибо!',failed:'Сообщение не отправлено. Попробуйте ещё раз.',top:'Наверх',light:'Светлая тема',dark:'Тёмная тема',present:'по настоящее время',studying:'Обучение продолжается',viewCertificate:'Посмотреть сертификат',navigation:'Навигация сайта',openMenu:'Открыть меню',closeMenu:'Закрыть меню',sampleNote:'Временный пример, а не реальное событие.'},
JP:{life:'日々の記録',lifeLabel:'学びとキャリア',sample:'サンプル',add:'記録を追加',edit:'編集',remove:'削除',save:'保存',saved:'保存しました',saving:'保存中…',cancel:'キャンセル',date:'日付',title:'タイトル',description:'説明',image:'画像',loading:'読み込み中…',unavailable:'データを読み込めませんでした。',empty:'まだデータがありません。',retry:'再試行',together:'一緒に取り組みましょう',credentials:'資格・修了証',tools:'ツールとアプローチ',journey:'職務経験',selected:'制作実績',talk:'お問い合わせ',contacts:'連絡先',required:'* 必須項目',sending:'送信中…',sent:'メッセージを送信しました。ありがとうございます。',failed:'送信できませんでした。もう一度お試しください。',top:'ページの先頭へ',light:'ライトテーマ',dark:'ダークテーマ',present:'現在',studying:'在学中',viewCertificate:'修了証を見る',navigation:'サイトナビゲーション',openMenu:'メニューを開く',closeMenu:'メニューを閉じる',sampleNote:'実際の出来事ではなく、仮のサンプルです。'}
};
export const textFor=language=>uiText[language]||uiText.ENG;
export const deviceLabel=(type,language)=>({UZ:{mobile:'Telefon',tablet:'Planshet',desktop:'Kompyuter',unknown:'Noma’lum'},ENG:{mobile:'Mobile',tablet:'Tablet',desktop:'Desktop',unknown:'Unknown'},RU:{mobile:'Телефон',tablet:'Планшет',desktop:'Компьютер',unknown:'Неизвестно'},JP:{mobile:'スマートフォン',tablet:'タブレット',desktop:'パソコン',unknown:'不明'}}[language]||{})[type]||type;
export const weekdayLabel=(day,language)=>({UZ:['Du','Se','Ch','Pa','Ju','Sh','Ya'],ENG:['Mon','Tue','Wed','Thu','Fri','Sat','Sun'],RU:['Пн','Вт','Ср','Чт','Пт','Сб','Вс'],JP:['月','火','水','木','金','土','日']}[language]||[])[['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].indexOf(day)]||day;
export function activityLabel(activity,language){const msg=activity.message||'',project=msg.startsWith("Yangi loyiha qo'shildi:"),name=msg.slice(msg.indexOf(':')+1).trim();return ({UZ:project?'Yangi loyiha qo‘shildi':'Yangi murojaat qabul qilindi',ENG:project?'New project added':'New message received',RU:project?'Добавлен новый проект':'Получено новое сообщение',JP:project?'新しいプロジェクトを追加':'新しいメッセージを受信'}[language]||'')+': '+name;}
export function activityTime(activity,language){if(!activity.timestamp)return '';const seconds=Math.max(0,(Date.now()-new Date(activity.timestamp).getTime())/1000),unit=seconds<60?'second':seconds<3600?'minute':seconds<86400?'hour':'day',amount=-Math.floor(seconds/({second:1,minute:60,hour:3600,day:86400}[unit]));if(language==='UZ')return seconds<60?'Hozirgina':`${-amount} ${({minute:'daqiqa',hour:'soat',day:'kun'})[unit]} oldin`;return new Intl.RelativeTimeFormat(({ENG:'en',RU:'ru',JP:'ja'})[language],{numeric:'auto'}).format(amount,unit);}
export function lifeDate(date,language){const value=new Date(date+'T12:00:00');if(language==='UZ')return `${value.getDate()}-${['yanvar','fevral','mart','aprel','may','iyun','iyul','avgust','sentabr','oktabr','noyabr','dekabr'][value.getMonth()]} ${value.getFullYear()}`;return new Intl.DateTimeFormat(({ENG:'en-GB',RU:'ru-RU',JP:'ja-JP'})[language],{year:'numeric',month:'short',day:'numeric'}).format(value);}
export const localizedPeriod=(value,language)=>String(value||'').replace(/O‘qish davom etmoqda \/ Currently studying|Currently studying|O‘qish davom etmoqda/gi,textFor(language).studying).replace(/hozir davom etyapti|hozir \/ Present|Present|hozir/gi,textFor(language).present);

const extra={
 UZ:{home:'Bosh sahifa',work:'ISHLAR',projects:'loyiha',search:'Loyihalarni qidirish…',all:'Barchasi',more:'Ko‘proq ko‘rish',noMatches:'Mos loyiha topilmadi.',clear:'Filtrlarni tozalash',download:'Yuklab olish',close:'Yopish',noImages:'Rasmlar hali yuklanmagan.',noResume:'Rezyume hali yuklanmagan.',previous:'Oldingi',next:'Keyingi',zoomIn:'Kattalashtirish',zoomOut:'Kichraytirish',fit:'Eniga moslash',gallery:'Rasmlar',images:'rasm'},
 ENG:{home:'Back home',work:'WORK',projects:'projects',search:'Search projects…',all:'All work',more:'Show more',noMatches:'No projects match your search.',clear:'Clear filters',download:'Download',close:'Close',noImages:'No images have been added yet.',noResume:'No résumé has been uploaded yet.',previous:'Previous',next:'Next',zoomIn:'Zoom in',zoomOut:'Zoom out',fit:'Fit to width',gallery:'Images',images:'images'},
 RU:{home:'На главную',work:'РАБОТЫ',projects:'проектов',search:'Поиск проектов…',all:'Все работы',more:'Показать ещё',noMatches:'Подходящие проекты не найдены.',clear:'Сбросить фильтры',download:'Скачать',close:'Закрыть',noImages:'Изображения ещё не добавлены.',noResume:'Резюме ещё не загружено.',previous:'Предыдущая',next:'Следующая',zoomIn:'Увеличить',zoomOut:'Уменьшить',fit:'По ширине',gallery:'Изображения',images:'изображений'},
 JP:{home:'ホームへ',work:'制作実績',projects:'件のプロジェクト',search:'プロジェクトを検索…',all:'すべて',more:'もっと見る',noMatches:'該当するプロジェクトがありません。',clear:'絞り込みを解除',download:'ダウンロード',close:'閉じる',noImages:'画像はまだ追加されていません。',noResume:'履歴書はまだアップロードされていません。',previous:'前へ',next:'次へ',zoomIn:'拡大',zoomOut:'縮小',fit:'幅に合わせる',gallery:'画像',images:'枚の画像'}
};
for(const language of Object.keys(extra))Object.assign(uiText[language],extra[language]);
for(const [language,portfolio,enterText] of [['UZ','Portfolio','Matnni kiriting'],['ENG','Portfolio','Enter text'],['RU','Портфолио','Введите текст'],['JP','ポートフォリオ','テキストを入力']])Object.assign(uiText[language],{portfolio,enterText});
