import {useState} from 'react';
import {useContent,localized} from '../lib/content';
import {adminFetch} from '../lib/adminApi';
import {textFor} from '../lib/uiText';
import ImageUpload from './ImageUpload';
export default function LifeAdmin({language}){
 const state=useContent('/api/life/',language),t=textFor(language),[form,setForm]=useState(null),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false),[status,setStatus]=useState('');
 const edit=item=>{setStatus('');setForm({...item,imageFile:null,imageRemoved:false});};
 async function save(e){e.preventDefault();if(busy||uploading)return;setBusy(true);setStatus('');try{const data=new FormData();for(const field of ['title','description'])for(const code of ['uz','en','ru','jp'])data.append(field+'_'+code,form[field+'_'+code]||'');data.append('title',form.title_uz);data.append('description',form.description_uz||'');data.append('date',form.date);data.append('is_sample',String(!!form.is_sample));if(form.imageFile)data.append('image',form.imageFile);else if(form.imageRemoved)data.append('image','');const r=await adminFetch(window.API_BASE_URL+'/api/life/'+(form.id?form.id+'/':''),{method:form.id?'PATCH':'POST',body:data,remoteOnly:true});if(!r.ok)throw new Error(JSON.stringify(await r.json()));setForm(null);setStatus(t.saved);state.retry();}catch(err){setStatus(err.message);}finally{setBusy(false);}}
 async function remove(item){if(!confirm(t.remove+' — '+localized(item,'title',language)+'?'))return;setBusy(true);try{const r=await adminFetch(window.API_BASE_URL+'/api/life/'+item.id+'/',{method:'DELETE',remoteOnly:true});if(r.ok)state.retry();else setStatus(t.failed);}catch(err){setStatus(err.message);}finally{setBusy(false);}}
 return <div><h3>{t.life}</h3><button className="button button-primary" onClick={()=>edit({date:new Date().toISOString().slice(0,10),is_sample:false})}>{t.add}</button>{status&&<p role="status">{status}</p>}{form?<form className="glass life-admin-form" onSubmit={save}><label>{t.date}<input type="date" value={form.date} required onChange={e=>setForm({...form,date:e.target.value})}/></label><ImageUpload kind="gallery" singleImage language={language} existing={[form.imageRemoved?null:form.image]} value={form.imageFile?[form.imageFile]:[]} onBusy={setUploading} onChange={files=>setForm(f=>({...f,imageFile:files[0]||null,imageRemoved:!files.length}))}/>{['uz','en','ru','jp'].map(code=><div key={code}><label>{code.toUpperCase()} · {t.title}<input required maxLength={180} value={form['title_'+code]||''} onChange={e=>setForm({...form,['title_'+code]:e.target.value})}/></label><label>{code.toUpperCase()} · {t.description}<textarea rows={3} value={form['description_'+code]||''} onChange={e=>setForm({...form,['description_'+code]:e.target.value})}/></label></div>)}<label><input type="checkbox" checked={!!form.is_sample} onChange={e=>setForm({...form,is_sample:e.target.checked})}/>{t.sample}</label><button type="submit" className="submit-btn" disabled={busy||uploading}>{busy?t.saving:t.save}</button><button type="button" className="cancel-btn" disabled={busy} onClick={()=>setForm(null)}>{t.cancel}</button></form>:<div className="life-admin-list">{(state.data||[]).map(item=><article className="glass" key={item.id}>{item.image&&<img src={item.image} alt="" width="100"/>}<h4>{localized(item,'title',language)}</h4><time>{item.date}</time><p>{localized(item,'description',language)}</p><button onClick={()=>edit(item)}>{t.edit}</button><button disabled={busy} onClick={()=>remove(item)}>{t.remove}</button></article>)}</div>}</div>;
}
